ITEM.name = "Katana"
ITEM.model = Model("models/weapons/charactersword.mdl")
ITEM.width = 3
ITEM.height = 1
ITEM.desc = "A katana. A more elegant weapon for a more civilized age."
ITEM.category = "Melee"
ITEM.price = 10000
ITEM.isWeapon = true
ITEM.class = "weapon_standardswordart"
